import os
import sys
from datetime import datetime, timezone

# AWS Glue / Spark imports
from awsglue.transforms import *  # noqa: F401,F403
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job

from pyspark.sql.functions import (
    col,
    length,
    lit,
    when,
    coalesce,
)
from pyspark.sql.types import (
    StringType,
    IntegerType,
    BooleanType,
    StructType,
    StructField,
)

# Initialize Glue/Spark context
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)

# Resolve Glue job args
args = getResolvedOptions(sys.argv, ['JOB_NAME'])
job.init(args['JOB_NAME'], args)

# CSV path from ENV with fallback to attachment path provided
csv_env_path = os.getenv("ASSET_CSV_PATH")
if not csv_env_path or not csv_env_path.strip():
    # Default to the attached CSV path if env var not set
    csv_path = "/home/kavia/workspace/code-generation/attachments/20251016_063111_SampleDump.csv"
    print(f"[INFO] ASSET_CSV_PATH not set. Falling back to default attachment path: {csv_path}")
else:
    csv_path = csv_env_path
    print(f"[INFO] Using CSV path from ASSET_CSV_PATH: {csv_path}")

# Define a schema that at least covers fields used for the mapping
# Additional columns are included as StringType to be permissive
csv_schema = StructType([
    StructField("TITLES_TITLE_ID", StringType(), True),  # Title ID
    StructField("PROGRAM_TITLE", StringType(), True),    # Preferred title name
    StructField("SERIES_TITLE", StringType(), True),     # Fallback title/series name
    StructField("ASSET_TYPE", StringType(), True),       # Potential title type
    StructField("TITLE_TYPE", StringType(), True),       # Alternative title type if present
    # Common fields from the previous job (kept as String for permissive loading)
    StructField("ASSET_UUID", StringType(), True),
    StructField("SEASON_TITLE", StringType(), True),
    StructField("SEASON_NUMBER", StringType(), True),
    StructField("PROPERTY_ID", StringType(), True),
    StructField("EPISODE_NUMBER", StringType(), True),
    StructField("CONTROLLING_NETWORK", StringType(), True),
    StructField("GLOBAL_RELEASE_YEAR", StringType(), True),
    StructField("REPACK_TYPE", StringType(), True),
    StructField("RL_ASSET_ID", StringType(), True),
    StructField("FABRIC_ID", StringType(), True),
    StructField("P2_PROGRAM_ID", StringType(), True),
])

print("[INFO] Reading CSV into Spark DataFrame...")
# Load CSV with robust options
df = (
    spark.read
    .option("header", True)
    .option("mode", "PERMISSIVE")
    .option("multiLine", True)
    .option("quote", '"')
    .option("escape", '"')
    .schema(csv_schema)
    .csv(csv_path)
)

print(f"[INFO] Loaded DataFrame with {df.count()} rows and columns: {df.columns}")

# Normalize key numeric-like fields if present (keep permissive otherwise)
# Casts are defensive; missing columns will be ignored by using getItem safely where required
if "SEASON_NUMBER" in df.columns:
    df = df.withColumn("SEASON_NUMBER", col("SEASON_NUMBER").cast(IntegerType()))
if "EPISODE_NUMBER" in df.columns:
    df = df.withColumn("EPISODE_NUMBER", col("EPISODE_NUMBER").cast(IntegerType()))
if "GLOBAL_RELEASE_YEAR" in df.columns:
    # Keep as string initially; we may cast derived column to int separately
    pass

# Filter out null/empty Title IDs and de-duplicate on TITLES_TITLE_ID
print("[INFO] Filtering null/empty Title IDs and de-duplicating...")
df_unique = (
    df.filter(col("TITLES_TITLE_ID").isNotNull() & (length(col("TITLES_TITLE_ID")) > 0))
      .dropDuplicates(["TITLES_TITLE_ID"])
)

print(f"[INFO] Unique by TITLES_TITLE_ID: {df_unique.count()} rows")

# Derive Title Name: PROGRAM_TITLE preferred; fallback to SERIES_TITLE
title_name_col = coalesce(col("PROGRAM_TITLE"), col("SERIES_TITLE"))

# Derive title_type using ASSET_TYPE then fallback to TITLE_TYPE
derived_title_type = coalesce(col("ASSET_TYPE"), col("TITLE_TYPE"))

# Build the Asset table mapping per business rules
# asset_id: None (assumed generated by DB), leave out or set null
# Fixed/default mappings:
# - asset_type_id: 68 (int)
# - asset_source_id: 'Titles'
# - business_entity_id: 'NA'
# - migrated_rms_id: 3 (int)
# - asset_group_id: 1 (int)
# - episode_number: 0 (int)
# - release_year: null (cast to Integer)
# - created_on / last_modified_on / imported_on: current UTC 'YYYY-MM-DD HH:MM:SS.SSS'
# - is_active: True (boolean)
print("[INFO] Deriving mapped Asset columns...")

# Prepare the timestamp string in UTC with millisecond precision
now_utc = datetime.now(timezone.utc)
# Ensure 3-digit milliseconds
formatted_ts = now_utc.strftime("%Y-%m-%d %H:%M:%S.") + f"{int(now_utc.microsecond / 1000):03d}"

asset_df = (
    df_unique
    .withColumn("asset_id", lit(None).cast(IntegerType()))
    .withColumn("asset_name", title_name_col)
    .withColumn("title_id", col("TITLES_TITLE_ID"))
    .withColumn("series_name", col("SERIES_TITLE"))
    .withColumn("title_type", derived_title_type)
    .withColumn("asset_type_id", lit(68).cast(IntegerType()))
    .withColumn("asset_source_id", lit("Titles").cast(StringType()))
    .withColumn("business_entity_id", lit("NA").cast(StringType()))
    .withColumn("migrated_rms_id", lit(3).cast(IntegerType()))
    .withColumn("asset_group_id", lit(1).cast(IntegerType()))
    .withColumn("episode_number", lit(0).cast(IntegerType()))
    .withColumn("release_year", lit(None).cast(IntegerType()))
    .withColumn("created_on", lit(formatted_ts).cast(StringType()))
    .withColumn("last_modified_on", lit(formatted_ts).cast(StringType()))
    .withColumn("imported_on", lit(formatted_ts).cast(StringType()))
    .withColumn("is_active", lit(True).cast(BooleanType()))
)

# String truncation safeguard similar to prior job
MAX_ALLOWED = 10000
TRIM_LENGTH = 9999
print("[INFO] Applying string length safeguard...")
for column in asset_df.columns:
    # Truncate only string-typed columns
    if asset_df.schema[column].dataType.simpleString() == "string":
        asset_df = asset_df.withColumn(
            column,
            when(length(col(column)) > MAX_ALLOWED, col(column).substr(1, TRIM_LENGTH)).otherwise(col(column))
        )

# Select and order columns for write (some DBs require explicit ordering)
# Note: Include only columns intended for the target Asset table
final_cols = [
    "asset_id",
    "asset_name",
    "title_id",
    "series_name",
    "title_type",
    "asset_type_id",
    "asset_source_id",
    "business_entity_id",
    "migrated_rms_id",
    "asset_group_id",
    "episode_number",
    "release_year",
    "created_on",
    "last_modified_on",
    "imported_on",
    "is_active",
]
final_df = asset_df.select(*final_cols)

print(f"[INFO] Final DataFrame columns: {final_df.columns}")
print(f"[INFO] Final DataFrame rows: {final_df.count()}")

# JDBC connection details from ENV
jdbc_url = os.getenv("ASSET_DB_URL") or "jdbc:postgresql://<HOST>:<PORT>/<DB_NAME>"  # Placeholder if missing
jdbc_user = os.getenv("ASSET_DB_USER") or "<DB_USER>"  # Placeholder if missing
jdbc_password = os.getenv("ASSET_DB_PASSWORD") or "<DB_PASSWORD>"  # Placeholder if missing
jdbc_table = os.getenv("ASSET_DB_TABLE") or "rights_canonical_schema.asset"  # Sensible default placeholder

if "<" in jdbc_url or "<" in jdbc_user or "<" in jdbc_password:
    print("[WARN] One or more DB ENV variables are not set. Using placeholders. "
          "Please set ASSET_DB_URL, ASSET_DB_USER, ASSET_DB_PASSWORD, and ASSET_DB_TABLE in environment.")

jdbc_props = {
    "user": jdbc_user,
    "password": jdbc_password,
    "driver": "org.postgresql.Driver",
}

print(f"[INFO] Writing to PostgreSQL table {jdbc_table} via {jdbc_url} in append mode...")
final_df.write.jdbc(url=jdbc_url, table=jdbc_table, mode="append", properties=jdbc_props)

print("[INFO] Write complete. Committing Glue job...")
job.commit()
